version: "3.1"
services:
  db:
    # Just going with a recent MySQL image, but specifying a version so it'll continue to work
    #  with this version of mysql-connector-python and won't drift. For info on compatibility
    #  of versions of MySQL and mysql-connector-python, see
    #  https://dev.mysql.com/doc/connector-python/en/connector-python-versions.html
    image: mysql:9.0.1
    restart: always
    ports:
      - "32000:3306"  # need port mapping if Flask app is running NOT in a container
    environment:
      # Password needs to match what's in mysql_repo.py
      MYSQL_ROOT_PASSWORD: strongpassword
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
