version: "3.1"
services:
  app:
    build:
      context: .
      # Within the Dockerfile, we'll give the command to start Flask, so that command doesn't need to be specified here
      dockerfile: Dockerfile
    environment:
      APP_ENV: docker
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    # Just going with a recent MySQL image, but specifying a version so it'll continue to work
    image: mysql:9.0.1
    restart: always
    environment:
      # Password needs to match what's in mysql_repo.py
      MYSQL_ROOT_PASSWORD: strongpassword
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
